// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package demo2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoRequest struct {
	StuName              string   `protobuf:"bytes,1,opt,name=stuName,proto3" json:"stuName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetStuName() string {
	if m != nil {
		return m.StuName
	}
	return ""
}

type SchoolResponse struct {
	SchoolName           string   `protobuf:"bytes,1,opt,name=schoolName,proto3" json:"schoolName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchoolResponse) Reset()         { *m = SchoolResponse{} }
func (m *SchoolResponse) String() string { return proto.CompactTextString(m) }
func (*SchoolResponse) ProtoMessage()    {}
func (*SchoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *SchoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchoolResponse.Unmarshal(m, b)
}
func (m *SchoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchoolResponse.Marshal(b, m, deterministic)
}
func (m *SchoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchoolResponse.Merge(m, src)
}
func (m *SchoolResponse) XXX_Size() int {
	return xxx_messageInfo_SchoolResponse.Size(m)
}
func (m *SchoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchoolResponse proto.InternalMessageInfo

func (m *SchoolResponse) GetSchoolName() string {
	if m != nil {
		return m.SchoolName
	}
	return ""
}

type AgeResponse struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgeResponse) Reset()         { *m = AgeResponse{} }
func (m *AgeResponse) String() string { return proto.CompactTextString(m) }
func (*AgeResponse) ProtoMessage()    {}
func (*AgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *AgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgeResponse.Unmarshal(m, b)
}
func (m *AgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgeResponse.Marshal(b, m, deterministic)
}
func (m *AgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgeResponse.Merge(m, src)
}
func (m *AgeResponse) XXX_Size() int {
	return xxx_messageInfo_AgeResponse.Size(m)
}
func (m *AgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgeResponse proto.InternalMessageInfo

func (m *AgeResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "demo2.InfoRequest")
	proto.RegisterType((*SchoolResponse)(nil), "demo2.SchoolResponse")
	proto.RegisterType((*AgeResponse)(nil), "demo2.AgeResponse")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xcc, 0x4b, 0xcb,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x49, 0xcd, 0xcd, 0x37, 0x52, 0x52, 0xe7,
	0xe2, 0xf6, 0xcc, 0x4b, 0xcb, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62,
	0x2f, 0x2e, 0x29, 0xf5, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71,
	0x95, 0x0c, 0xb8, 0xf8, 0x82, 0x93, 0x33, 0xf2, 0xf3, 0x73, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0xe4, 0xb8, 0xb8, 0x8a, 0xc1, 0x22, 0x48, 0xca, 0x91, 0x44, 0x94, 0xe4, 0xb9,
	0xb8, 0x1d, 0xd3, 0x53, 0xe1, 0xca, 0x05, 0xb8, 0x98, 0x13, 0xd3, 0x21, 0xea, 0x58, 0x83, 0x40,
	0x4c, 0xa3, 0x72, 0x2e, 0xde, 0xf4, 0xd4, 0x12, 0x90, 0xf5, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45,
	0x42, 0x26, 0x5c, 0xec, 0xee, 0xa9, 0x25, 0x20, 0xcd, 0x42, 0x42, 0x7a, 0x60, 0xf7, 0xe9, 0x21,
	0x39, 0x4e, 0x4a, 0x14, 0x2a, 0x86, 0xe6, 0x0e, 0x03, 0x2e, 0x36, 0xf7, 0xd4, 0x12, 0xc7, 0x74,
	0xec, 0x9a, 0x60, 0x62, 0x48, 0x4e, 0x49, 0x62, 0x03, 0x07, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xb6, 0xfd, 0xfe, 0x46, 0x10, 0x01, 0x00, 0x00,
}
